### PR TITLE
Update to using the `jupyterlite` cli

### PR DESCRIPTION
**Pull request by jtpio**
Simplify the setup using the published `jupyterlite` CLI.

### CODE REVIEW

**Comment by jtpio** [comment]
cc @psychemedia @giswqs
 
This streamlines the deployment of JupyterLite applications, using the recently published `jupyterlite` package on PyPI: https://pypi.org/project/jupyterlite/0.1.0a1/

**Comment by psychemedia** [comment]
@jtpio Ooh, exciting. So from a quick look I just need to `jupyter lite init && jupyter lite build` and I get a site? Will try to have a play tomorrow. Not sure I immediately grok sense of `jupyter-lite.json` and `overrides.json`, or how to pre-install additional pip packages (maybe via those files?). Thanks for the heads-up:-)

**Comment by jtpio** [comment]
> or how to pre-install additional pip packages (maybe via those files?)

The `jupyter lite build` step should copy existing jupyterlab extensions installed in the same virtual environment.

`overrides.json` is useful to control JupyterLab settings and extensions.

**Comment by jtpio** [comment]
> `overrides.json` is useful to control JupyterLab settings and extensions.

Added an example in https://github.com/jtpio/jupyterlite-demo/pull/7

**Pull request merged**
